name: Build snapshot
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Arch Linux package
        uses: ./
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
          OUTDIR: $HOME/arch-packages
      - name: Build the package again
        uses: ./
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
          OUTDIR: $HOME/arch-packages2
